version: '3.8'
 
services:
  db:
    image: mysql:5.7
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: studentsdb
    ports:
      - "3306:3306"
 
  web:
    image: shivani138/python_cicd_image:latest
    container_name: flask-app
    ports:
      - "5000:5000"
    depends_on:
      - db
